# Generated by Django 3.2 on 2023-06-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('hours_min', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('appointment_total_price', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('streetNumber', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='AppointmentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photographer.activity')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.appointment')),
            ],
            options={
                'db_table': 'appointment_activity',
            },
        ),
        migrations.CreateModel(
            name='Appointment_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurance_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.appointment')),
            ],
            options={
                'db_table': 'Appointment_manager',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='photographer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photographer.photographer'),
        ),
    ]
